# Generated by Django 5.2.6 on 2025-10-04 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientmodel',
            name='core_client_email_5232e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientmodel',
            name='core_client_manage__7a6cf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='core_custom_email_a5d01e_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='auth_user_first_n_199799_idx',
            old_name='core_custom_first_n_460402_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clientmodel',
            unique_together={('email', 'partition_key')},
        ),
        migrations.RemoveField(
            model_name='leadmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='client_tier',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('basic', 'Basic')], db_index=True, default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='country_code',
            field=models.CharField(db_index=True, default='US', max_length=3),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='partition_key',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='partition_key',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signup_source',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='designationmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designationmodel',
            name='hierarchy_level',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='designationmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='partition_key',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='manage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to='core.leadmodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designationmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.designationmodel'),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='experience',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['email', 'status'], name='clients_email_650360_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['manage_by', 'status'], name='clients_manage__3575db_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['client_tier', 'status'], name='clients_client__dcd75c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['country_code', 'created_at'], name='clients_country_e95a28_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['partition_key', 'status'], name='clients_partiti_e2859f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='auth_user_email_db7920_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='auth_user_created_2cecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['partition_key', 'is_active'], name='auth_user_partiti_a80645_idx'),
        ),
        migrations.AddIndex(
            model_name='designationmodel',
            index=models.Index(fields=['name', 'is_active'], name='designation_name_fc4ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='designationmodel',
            index=models.Index(fields=['hierarchy_level'], name='designation_hierarc_72c725_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmodel',
            index=models.Index(fields=['user', 'status'], name='leads_user_id_57eab3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmodel',
            index=models.Index(fields=['designation', 'status'], name='leads_designa_82c226_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmodel',
            index=models.Index(fields=['salary'], name='leads_salary_8adffe_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmodel',
            index=models.Index(fields=['created_at', 'status'], name='leads_created_836b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmodel',
            index=models.Index(fields=['partition_key', 'is_archived'], name='leads_partiti_bedb62_idx'),
        ),
        migrations.AlterModelTable(
            name='clientmodel',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='designationmodel',
            table='designations',
        ),
        migrations.AlterModelTable(
            name='leadmodel',
            table='leads',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='contact',
        ),
    ]
